trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'myimage'
  registryName: 'containerregistrypetruadelinpricop30643.azurecr.io'

pool:
  name: 'local'  # Self-hosted agent pool

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push Docker Image
    pool:
      name: 'local'  # Ensure the self-hosted agent pool is being used
    steps:
    - script: echo "This job should run on the self-hosted agent!"
    
    # Step to log in to Azure using CLI
    - script: |
        echo "Logging in to Azure..."
        az login  # Authenticate with Azure CLI
        az acr login --name containerregistrypetruadelinpricop30643  # Authenticate to Azure Container Registry
      displayName: 'Login to Azure and ACR'
      
    # Step to build Docker image
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        dockerfile: '$(Build.SourcesDirectory)/chatMicroservice/Dockerfile'
        tags: |
          $(registryName)/$(imageName):$(tag)

    # Step to push Docker image
    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        command: 'push'
        containerRegistry: 'containerregistrypetruadelinpricop30643.azurecr.io'
        repository: '$(registryName)/$(imageName)'
        tags: |
          $(tag)
