trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'myimage'  # Adjust the image name as needed
  registryName: 'containerregistrypetruadelinpricop30643'

pool:
  name: 'local'  # Self-hosted agent pool

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push Docker Image
    pool:
      name: 'local'  # Ensure the self-hosted agent pool is being used
    steps:
    - script: echo "This job should run on the self-hosted agent!"
    
    - task: Docker@2
      displayName: 'Login to Azure Container Registry'
      inputs:
        command: 'login'
        containerRegistry: 'containerregistrypetruadelinpricop30643'

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        dockerfile: '$(Build.SourcesDirectory)/chatMicroservice/Dockerfile'
        tags: |
          $(registryName)/$(imageName):$(tag)
    
    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        command: 'push'
        containerRegistry: 'containerregistrypetruadelinpricop30643'
        repository: '$(registryName)/$(imageName)'
        tags: |
          $(tag)
